### ISSUE TITLE
I think its working as intended for dose and vaccine filter now

### ISSUE THREAD

**Issue by pranshusugara** [veenaypatil/Vaccine-Slot-Info#11]
I followed all the instructions, which were very well written and easy to setup and ran all the commands. 

There are issues with the commands. 

1 Issue with command: slotinfo district-wise --district_id 294 --date 24-05-2021 --age_filter 18 --notify_on telegram (Most important)

The command above shows booked slots, not the slots available in real time. May require some modification to flag only the _change_ in status. 

![Screenshot of issue no 1](https://user-images.githubusercontent.com/57094152/119259410-d890a980-bbeb-11eb-8c45-e847ed3b8411.png)

2. Issue with command: continuously for district

This command returns the first pincode 560001(Vikram hospital) and again shows booked slots, not the slots available in real time.

![Screenshot for issue command 2](https://user-images.githubusercontent.com/57094152/119259511-4937c600-bbec-11eb-9eea-03c5df57e8da.png)

Consequently the telegram bot shows this non stop a 1 min, 2 min, 3 min and 6 min intervals

![Screenshot for command 2 issues in telegram](https://user-images.githubusercontent.com/57094152/119259710-13471180-bbed-11eb-8a49-02bbe88e5e81.png)

3. Issue with command continuously for district for 7 days

Command doesn't exist...might have been removed as it doesn't work? Just guessing. 

![Screenshot for command 3](https://user-images.githubusercontent.com/57094152/119259820-ac762800-bbed-11eb-8949-9dacca279d3b.png)

@veenaypatil : Will you be working to resolve these or do you suggest any other bot ? Appreciate a preliminary response of your intent so I can wait for this or try other solutions please. 

Thanks once again for the amazing python alternative, it was very easy to follow and setup and learnt a lot from your attempt.

**Comment by veenaypatil** [comment]
@pranshusugara 

> The command above shows booked slots, not the slots available in real time

This should not be the case, recently the Cowin web has modified to show the slots according to Dose1 or Dose2, that is why even if you receive a notification on Telegram/Whatsapp it can happen that the slots are shown as booked on the UI. We are working on a change to filter out according to dose number which should send correct notification. The release for the same should be available today itself (will notify you).

> Consequently the telegram bot shows this non stop a 1 min, 2 min, 3 min and 6 min intervals

This is expected as the cache TTL is kept to 1 minute, should I keep this default to 10 minutes to avoid the noise ?

**Comment by veenaypatil** [comment]
> Command doesn't exist...might have been removed as it doesn't work? Just guessing.

Make sure to download the correct Tar from Release section and not from the Assets

**Comment by pranshusugara** [comment]
Yes I do have v1.1 and not v1.0...

Will wait for v1.3 that has the dose 1 filter

Yes removing noise is preferable.

Thanks so much for the quick response.

**Comment by veenaypatil** [comment]
@pranshusugara  Created a new release - https://github.com/veenaypatil/Vaccine-Slot-Info/releases/tag/v1.2
You can now filter based on dose number and vaccine type as well (check cmds usage in readme)

**Comment by pranshusugara** [comment]
Thank you so much.

I hope this is working now: 

![screenshot its working](https://user-images.githubusercontent.com/57094152/119264822-4c3db100-bc02-11eb-97f1-740ecfccd32e.png)

**Comment by veenaypatil** [comment]
Thanks for confirming , closing the issue
