### ISSUE TITLE
How do i give multiple dates and zip codes ?

### ISSUE THREAD

**Issue by achadaga** [veenaypatil/Vaccine-Slot-Info#6]
How do i give multiple dates and zip codes ?
Also, the telegram bot. I created one, but only i am getting notification. No one else is getting notification. Any idea why ?

**Comment by veenaypatil** [comment]
@achadaga Thank you for opening the first issue 😄 

> How do i give multiple dates and zip codes ?

Currently, I have added new commands to check for appointment slots for next 7 days, will that help here ?

> Also, the telegram bot. I created one, but only i am getting notification. No one else is getting notification. Any idea why ?

This is expected, bot is specific to your account only, only you will be notified

**Comment by achadaga** [comment]
> @achadaga Thank you for opening the first issue 😄
> 
> > How do i give multiple dates and zip codes ?
> 
> Currently, I have added new commands to check for appointment slots for next 7 days, will that help here ?
> 
> > Also, the telegram bot. I created one, but only i am getting notification. No one else is getting notification. Any idea why ?
> 
> This is expected, bot is specific to your account only, only you will be notified

Yes,that is indeed helpful.
