### ISSUE TITLE
Filter slots by vaccine

### ISSUE THREAD

**Issue by IAmSalvaMartini** [veenaypatil/Vaccine-Slot-Info#9]
Would it be possible to add a filter so we get notifications only for a specific vaccine which we specify? This would also lead to less spammy notifications

**Comment by veenaypatil** [comment]
@IAmSalvaMartini  yes that is definitely possible ? would you like to contribute ?

**Comment by veenaypatil** [comment]
Assigning to @mbarbind to take this forward

**Comment by IAmSalvaMartini** [comment]
> @IAmSalvaMartini yes that is definitely possible ? would you like to contribute ?

Hey, I'm not very familiar with python but I appreciate adding @mbarbind , thanks

**Comment by IAmSalvaMartini** [comment]
The protected API has an option to filter vaccine https://api.demo.co-vin.in/api/v2/appointment/sessions/calendarByPin?pincode=600004&date=22-05-2021&vaccine=COVAXIN, but it doesn't work with the production API

**Comment by veenaypatil** [comment]
@IAmSalvaMartini  we can take the vaccine option from the user and filter it as well, just like we do for age right now

**Comment by veenaypatil** [comment]
@IAmSalvaMartini Created a new release - https://github.com/veenaypatil/Vaccine-Slot-Info/releases/tag/v1.2
You can now filter based on dose number and vaccine type as well (check cmds usage in readme)

**Comment by IAmSalvaMartini** [comment]
> @IAmSalvaMartini Created a new release - https://github.com/veenaypatil/Vaccine-Slot-Info/releases/tag/v1.2
> You can now filter based on dose number and vaccine type as well (check cmds usage in readme)

That was quick, thank you so much for the prompt addition
